workflows:
  android-build:
    name: Build APK
    environment:
      flutter: stable

    scripts:
      - cd baccarat-final888-app/android_splash_screen
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - baccarat-final888-app/android_splash_screen/build/app/outputs/flutter-apk/app-release.apk
